# Generated by Django 3.2.5 on 2021-09-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210914_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=200),
        ),
    ]
